import { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  return knex.raw(`
    CREATE TABLE users (
      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email text,
      name text,
      password text
    );
  `);
}

export async function down(knex: Knex): Promise<void> {
  return knex.raw(`
    DROP TABLE users;
  `);
}
